/**
 * Segmentos do site LicitaNet (https://licitanet.com.br/boletim) — id e nome exatamente
 * como o próprio site os expõe (parâmetro `codSegments` da busca). Não é uma taxonomia
 * nossa; é fixa porque vem de um terceiro que não oferece uma API para consultá-la, só
 * embutida na página. Reveja esta lista se o site reorganizar seus segmentos.
 */
export type SegmentoLicitaNet = { id: number; nome: string };

export const SEGMENTOS_LICITANET: SegmentoLicitaNet[] = [
  { id: 161, nome: "Abate de Animais" },
  { id: 28, nome: "Acondicionamento / Embalagens / Descartáveis" },
  { id: 56, nome: "Alarmes / Videos / Cercas elétricas / Sensores / Blindagens" },
  { id: 2, nome: "Alimentação especial (Dieta restritiva, Suplementos)" },
  { id: 44, nome: "Aluguel de Veículos Leves / Pesados" },
  { id: 136, nome: "Ambulâncias" },
  { id: 166, nome: "Aquisição de Cama, Mesa e Banho" },
  { id: 103, nome: "Aquisição de Máquinas e equipamentos para Construção" },
  { id: 96, nome: "Aquisição de máquinas pesadas" },
  { id: 46, nome: "Aquisição de Motocicletas" },
  { id: 163, nome: "Aquisição de Tintas Imobiliarias" },
  { id: 198, nome: "Aquisição de tintas para sinalização viária" },
  { id: 170, nome: "Aquisição de utensílios de copa e cozinha" },
  { id: 45, nome: "Aquisição de Veículos Leves" },
  { id: 49, nome: "Aquisição de Veículos Pesados" },
  { id: 124, nome: "Armarinhos / Tecidos" },
  { id: 53, nome: "Armas e Munições" },
  { id: 35, nome: "Artigos e Equipamentos Esportivos" },
  { id: 131, nome: "Assessoria / Consultoria em Geral" },
  { id: 59, nome: "Assessoria Administrativa" },
  { id: 58, nome: "Assessoria Contábil" },
  { id: 92, nome: "Atividades Geotécnicas" },
  { id: 177, nome: "Avaliação de Imóveis" },
  { id: 201, nome: "Bandeiras Oficiais, Flâmulas e Insígnas" },
  { id: 133, nome: "Bens Imóveis" },
  { id: 141, nome: "Bens Imóveis" },
  { id: 132, nome: "Bens Móveis" },
  { id: 140, nome: "Bens Móveis" },
  { id: 169, nome: "Bicicleta Elétrica" },
  { id: 83, nome: "Cartuchos e Tonner" },
  { id: 78, nome: "Castração de Animal / Castramóvel / Serviços de PetShop" },
  { id: 87, nome: "Certificação digital" },
  { id: 6, nome: "Cestas Básicas / Cestas de Natal" },
  { id: 18, nome: "Chaveiro" },
  { id: 148, nome: "Cirurgias Eletivas" },
  { id: 158, nome: "Concessão de Uso" },
  { id: 24, nome: "Concessões / Exploração / Imóvel" },
  { id: 25, nome: "Concursos Públicos / Processos Seletivos" },
  { id: 101, nome: "Construção de Estruturas (Pontes /Túneis / Viadutos / Marítimos" },
  { id: 102, nome: "Construção de Habitações / Armazéns / Estruturas Metálicas" },
  { id: 17, nome: "Contratação de Serviços Terceirizados" },
  { id: 152, nome: "Contratação de Serviços Terceirizados - Motorista" },
  { id: 145, nome: "Convênio médico ou serviços médicos" },
  { id: 149, nome: "Convênios Odontológicos." },
  { id: 31, nome: "Cursos / Palestras / Treinamentos" },
  { id: 38, nome: "Decoração" },
  { id: 108, nome: "Dedetização / Descupinização e assemelhados" },
  { id: 3, nome: "Demais itens da Alimentação (perecíveis e não perecíveis)" },
  { id: 206, nome: "Demolição e Desmonte de Estruturas" },
  { id: 13, nome: "Desinfecção / Desinsetização / Desratização" },
  { id: 36, nome: "Eletrodomésticos / Eletroportáteis / Eletroeletrônicos" },
  { id: 138, nome: "Embarcação Motorização / Acessórios" },
  { id: 61, nome: "Emissão / Cancelamento de Passagem" },
  { id: 191, nome: "Equipamento/instrumento para pesquisa cientifica e tecnológica" },
  { id: 100, nome: "Equipamentos / Geração / Transmissão de Energia" },
  { id: 32, nome: "Equipamentos / Instrumentos Musicais" },
  { id: 52, nome: "Equipamentos / materiais e Acessórios de Segurança" },
  { id: 85, nome: "Equipamentos / Serviços de Internet" },
  { id: 84, nome: "Equipamentos / Serviços de Telecomunicação / Telefonia" },
  { id: 202, nome: "Equipamentos Agroindustriais" },
  { id: 64, nome: "Equipamentos e máquinas agrícolas" },
  { id: 178, nome: "Equipamentos e material de processamento de dados" },
  { id: 179, nome: "Equipamentos energéticos - dispositivos que geram, armazenam, controlam ou consomem energia elétrica" },
  { id: 69, nome: "Equipamentos Hospitalares" },
  { id: 71, nome: "Equipamentos Médicos" },
  { id: 192, nome: "Equipamentos/Instrumento/partes e peças e acessórios para pesquisa científica e tecnológica." },
  { id: 79, nome: "Eventos / Produções Audiovisuais / Estrutura de Palco" },
  { id: 73, nome: "Exames / Equipamentos Laboratoriais" },
  { id: 74, nome: "Fabricação / Materiais para Óculos / Lentes" },
  { id: 174, nome: "Fabricação e instalação de coifas em inox " },
  { id: 37, nome: "Ferramentas em geral" },
  { id: 162, nome: "Fertilizantes e Sementes" },
  { id: 185, nome: "Filmagem, transmissão de evento corporativo, shows" },
  { id: 175, nome: "Fiscalização de Obras" },
  { id: 129, nome: "Fogos de Artificio" },
  { id: 29, nome: "Fornecimento de Água/Gás/Gelo" },
  { id: 125, nome: "Fornecimento de Brinquedos Infantis / Locação / Instalação" },
  { id: 40, nome: "Fornecimento de Combustível" },
  { id: 90, nome: "Fornecimento de Hardwares e Periféricos" },
  { id: 5, nome: "Fornecimento de Marmitas" },
  { id: 110, nome: "Fornecimento de Materiais de Limpeza / Higiene" },
  { id: 4, nome: "Fornecimento de Merenda" },
  { id: 65, nome: "Fornecimento de produtos, Aparelhos  Veterinários" },
  { id: 86, nome: "Fornecimento de Softwares / Licença de Softwares / Locação de Aplicativos" },
  { id: 144, nome: "Frete de embarcação" },
  { id: 72, nome: "Gases Medicinais" },
  { id: 176, nome: "Gerenciamento de Obras" },
  { id: 89, nome: "Gestão eletrônica de documentos (Serviços de Gestão)" },
  { id: 180, nome: "GPS e equipamentos e material para áudio, vídeo e foto" },
  { id: 139, nome: "Guincho / Reboque" },
  { id: 160, nome: "Herbicidas e Inseticidas" },
  { id: 1, nome: "Hortifruti" },
  { id: 60, nome: "Hospedagem / Hotelaria" },
  { id: 181, nome: "Imóvel urbano ou rural" },
  { id: 63, nome: "Implementos / Materiais de inseminação e Alimentação Animal" },
  { id: 19, nome: "Instalação / Manutenção de Ar condicionado" },
  { id: 99, nome: "Instalação / Manutenção Elevadores" },
  { id: 204, nome: "Insumos, Materiais e Suprimentos Hospitalares" },
  { id: 82, nome: "Jornais / Revistas" },
  { id: 26, nome: "Leilões" },
  { id: 51, nome: "Limpeza de Veículos" },
  { id: 12, nome: "Limpeza publica / Coleta de Lixo" },
  { id: 134, nome: "Livros / Livraria" },
  { id: 94, nome: "Locação de Máquinas e equipamentos para Construção" },
  { id: 123, nome: "Locação de Máquinas Pesadas / com ou sem motorista" },
  { id: 184, nome: "Locação de tendas/estruturas" },
  { id: 157, nome: "Madeiras" },
  { id: 150, nome: "Manutenção de equipamentos" },
  { id: 205, nome: "Manutenção de Equipamentos Odontológicos/Hospitalares" },
  { id: 194, nome: "Manutenção preventiva e corretiva para câmaras frias" },
  { id: 8, nome: "Mão de obra copa, cozinha, garçon" },
  { id: 93, nome: "Massa Asfáltica / CBUQ / Concreto usinado" },
  { id: 173, nome: "Mata-Burro (fosso escavado com travessas espaçadas)" },
  { id: 75, nome: "Materiais / Suprimentos / Equipamentos  Odontológicos" },
  { id: 30, nome: "Materiais de Expediente" },
  { id: 95, nome: "Materiais para construção / Materiais Elétricos" },
  { id: 203, nome: "Materiais Permanentes - Fisioterapia, Educação Física, Pilates, Musculação." },
  { id: 156, nome: "Materiais pré-moldados" },
  { id: 43, nome: "Mecânica em Geral" },
  { id: 164, nome: "Medicação/Drogas Animais" },
  { id: 68, nome: "Medicamentos" },
  { id: 153, nome: "Medição de gás / água / energia" },
  { id: 33, nome: "Mobílias em Geral" },
  { id: 186, nome: "Motobombas, peneiras e aspirador para limpeza de piscinas" },
  { id: 189, nome: "Móveis planejados em MDF" },
  { id: 183, nome: "Mudas de Espécies Arbóreas" },
  { id: 41, nome: "Óleos / Filtros / Lubrificantes" },
  { id: 137, nome: "Ônibus, mini ônibus e furgão" },
  { id: 147, nome: "OUTSOURCING - Locação de equipamentos, para a reprodução ou digitalização de documentos" },
  { id: 159, nome: "Ovos de Páscoa" },
  { id: 16, nome: "Paisagismo / Gramas / Flores" },
  { id: 142, nome: "Passagem Expressa Pedágio (TAG ou TIV)" },
  { id: 187, nome: "PCMSO, PGR, LTCAT, LTIP, LIP, Engenharia de Segurança do trabalho, SESMT, Higiene Ocupacional, Mediç" },
  { id: 42, nome: "Peças de Veículos / Motocicletas" },
  { id: 155, nome: "Peças para gás" },
  { id: 81, nome: "Pesquisa" },
  { id: 167, nome: "Placas Mercosul" },
  { id: 39, nome: "Pneus e Serviços de Borracharia" },
  { id: 104, nome: "Poços Artesianos / Aquisição de materiais / Manutenção e Peças" },
  { id: 88, nome: "Ponto eletrônico / Bobinas Térmicas" },
  { id: 55, nome: "Prevenção / Combate a incêndio" },
  { id: 70, nome: "Procedimentos Hospitalares" },
  { id: 91, nome: "Projetos Arquitetura / Engenharia Civil / Elétrica" },
  { id: 67, nome: "Projetos e Obras de Irrigação ou Agrícolas" },
  { id: 77, nome: "Próteses em Geral" },
  { id: 80, nome: "Publicidade / Propaganda / Comunicação / Marketing" },
  { id: 27, nome: "Químicos / Bioquímicos" },
  { id: 50, nome: "Rastreamento Veicular / Seguros" },
  { id: 182, nome: "Robótica" },
  { id: 168, nome: "Saneamento Básico / Destinação de Resíduos / Aterro Sanitário" },
  { id: 127, nome: "Seguros de Vida" },
  { id: 146, nome: "Serviço de gerenciamento de compras" },
  { id: 143, nome: "Serviço de pintura em veículos" },
  { id: 23, nome: "Serviço de Seguros" },
  { id: 106, nome: "Serviços / Materiais Funerários e Translado" },
  { id: 66, nome: "Serviços / Peças de Máquinas Pesadas" },
  { id: 196, nome: "Serviços de Apresentações Artísticas, Atividades Culturais Educativas e Pedagógicas" },
  { id: 128, nome: "Serviços de Arqueologia / Geologia / Escavação" },
  { id: 9, nome: "Serviços de Buffet / Lanches" },
  { id: 14, nome: "Serviços de Esporte e Lazer" },
  { id: 126, nome: "Serviços de Gráfica / Impressão" },
  { id: 193, nome: "Serviços de Instalação, Manutenção e Adequação de Superfícies Envidraçadas e Esquadrias" },
  { id: 57, nome: "Serviços de Instituição Financeira" },
  { id: 195, nome: "Serviços de Manutenção, Usinagem, Solda e Recuperação de Equipamentos e Estruturas Metálicas" },
  { id: 97, nome: "Serviços de obras / construção" },
  { id: 197, nome: "Serviços de Sonorização, Trio Elétrico e Publicidade Volante" },
  { id: 54, nome: "Serviços de Vigilância / Patrimonial / Serviços de Portaria" },
  { id: 105, nome: "Serviços e Aquisição de Tratamento de água" },
  { id: 98, nome: "Serviços elétricos" },
  { id: 199, nome: "Serviços Metalúrgicos e de Manutenção Mecânica" },
  { id: 21, nome: "Serviços Musicais / Instrumentos / Bandas" },
  { id: 200, nome: "Serviços Técnicos de Patrimônio Público" },
  { id: 130, nome: "Show Pirotécnico" },
  { id: 117, nome: "Sinalização / Comunicação Visual / Placas" },
  { id: 76, nome: "Suprimentos / Aparelhos Auditivos" },
  { id: 154, nome: "Tradução / interpretação de Libras" },
  { id: 171, nome: "Trailer" },
  { id: 62, nome: "Translado e Guia de Turismo" },
  { id: 48, nome: "Transporte de Cargas" },
  { id: 172, nome: "Transporte de cargas." },
  { id: 188, nome: "Transporte de Passageiros e/ou Escolar" },
  { id: 47, nome: "Transportes Escolar" },
  { id: 7, nome: "Utensílios de Cozinha" },
  { id: 10, nome: "Vale alimentação / Refeição" },
  { id: 165, nome: "Veículo tipo Gaiola Boiadeira" },
  { id: 34, nome: "Vestuário / Uniformes / Calçados" },
  { id: 135, nome: "Vidros e/ou Espelhos" },
];

export function nomeSegmentoLicitaNet(id: number): string | undefined {
  return SEGMENTOS_LICITANET.find((s) => s.id === id)?.nome;
}
